global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-apps"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "config-server:8888"
          - "discovery-service:8761"
          - "api-gateway:8080"
