server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    default: dev
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 10

  config:
    import: "configserver:"
