name: Deploy config-server

on:
  push:
    branches: '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: chmod
        run: chmod +x gradlew

      - name: Build Docker image
        run: docker build -t stannisl/kfd-user-service:${{ steps.sha.outputs.sha }} -t stannisl/kfd-user-service:latest -f Dockerfile .

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push stannisl/kfd-user-service:${{ steps.sha.outputs.sha }}
          docker push stannisl/kfd-user-service:latest
